CREATE TABLE "shipments" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "shipments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status" varchar(50) NOT NULL,
	"cargo" jsonb NOT NULL,
	"autoTrackingStatus" varchar(50) NOT NULL,
	"cancelledAt" timestamp,
	"customerReference" varchar(255),
	"houseBlConsignee" jsonb,
	"houseBlShipper" jsonb,
	"label" jsonb,
	"responsibilityType" varchar(50) NOT NULL,
	"tradeDirection" varchar(50) NOT NULL,
	"urgencyLevel" varchar(50) NOT NULL,
	"transshipPorts" jsonb,
	"pol" jsonb,
	"pod" jsonb,
	"freetimeLimitDate" timestamp,
	"dem" integer,
	"det" integer,
	"assignedPartners" jsonb,
	"internalAssignees" jsonb,
	"assignedPartnerTeams" jsonb,
	"totalUnreadMessageCount" integer NOT NULL,
	"handledBySimpleOperations" boolean NOT NULL
);
